- name: Run weatherapp
  hosts: aws
  remote_user: "ubuntu"
  
  
  tasks:
  - name: Launch Docker-compose
    become: true
    docker_service:
      project_src: weatherapp/
      state: present
#    - name: Clone repo
#      git:
#        repo: "https://github.com/harmittaa/weatherapp.git"
#        dest: /home/ubuntu/weatherapp/
