- name: Install Docker
  hosts: awsnew
  remote_user: "ubuntu"
  become: true
  gather_facts: False
  pre_tasks:
    - raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

  #for installing Docker
  # https://www.digitalocean.com/community/tutorials/how-to-install-and-   # use-docker-on-ubuntu-16-04
  tasks:
    - name: Test message
      debug: msg="Ansible is working!"
    - name: Add GPG key
      raw: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    - name: Add to APT sources
      raw: sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    - name: Update package DB
      raw: sudo apt-get update
    - name: Install Docker
      raw: sudo apt-get install -y docker-ce
    - name: Install Docker-compose
      raw: sudo apt-get install -y docker-compose